# Generated by Django 2.0.7 on 2018-07-12 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Booked Dock',
            },
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Dock',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='close_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='opened_overnight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docks.Warehouse'),
        ),
        migrations.AddField(
            model_name='bookeddock',
            name='dock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docks.Dock'),
        ),
    ]
