# Generated by Django 2.0.7 on 2018-07-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dock',
            unique_together={('warehouse', 'name')},
        ),
    ]
