# Generated by Django 2.0.7 on 2018-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docks', '0002_auto_20180714_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
    ]
