# Generated by Django 2.0.7 on 2018-07-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docks', '0002_auto_20180714_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookeddock',
            name='po_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookeddock',
            name='truck_number',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
