# Generated by Django 2.0.7 on 2018-07-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehousemanager',
            unique_together=set(),
        ),
    ]
